/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-20 03:32:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminProductInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"adminError.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>lookbom</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/lb/resources/css/productadmin.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   var i = 1;\r\n");
      out.write(" function addRow(){\r\n");
      out.write("\t\tvar row = \"<tr height='40'><td align='center' ><input type='color' name='productcolor' id='productcolor'></td>\"+\r\n");
      out.write("\t\t\"<td><input type='file'  name='\"+i+\"productimage1' id='\"+i+\"productimage1'></td>\"+\r\n");
      out.write("\t\t\"<td><input type='file'  name='\"+i+\"productimage2' id='\"+i+\"productimage2'></td>\"+\r\n");
      out.write("\t\t\"<td><input type='file'  name='\"+i+\"productimage3' id='\"+i+\"productimage3'></td>\"+\r\n");
      out.write("\t\t\"<td><input type='file'  name='\"+i+\"productimage4' id='\"+i+\"productimage4'></td>\"+\r\n");
      out.write("\t\t\"<td><input type='file'  name='\"+i+\"productimage5' id='\"+i+\"productimage5'></td>\"+\r\n");
      out.write("\t\t\"<td align='center'><input type='text' size='10' name='ssizequantity' id='ssizequantity'></td>\"+\r\n");
      out.write("\t\t\"<td align='center'><input type='text' size='10' name='msizequantity' id='msizequantity'></td>\"+\r\n");
      out.write("\t\t\"<td align='center'><input type='text' size='10' name='lsizequantity' id='lsizequantity'></td>\"+\r\n");
      out.write("\t\t\"<td align='center'><input type='text' size='10' name='xlsizequantity' id='xlsizequantity'></td>\"+\r\n");
      out.write("\t\t\"</tr>\";\t\t\r\n");
      out.write("\t\t document.getElementById(\"productdetail\").innerHTML += row;\r\n");
      out.write("\t\t i++;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form name=\"product\" id=\"product\" method=\"post\" action=\"/lb/apinsert\" enctype=\"multipart/form-data\">\r\n");
      out.write("<h2 align=\"center\">상품등록페이지</h2>\r\n");
      out.write("<table align=\"center\" width=\"1200\">\r\n");
      out.write("<tr align=\"left\"><th>상품등록</th></tr>\r\n");
      out.write("</table>\r\n");
      out.write("<hr align=\"center\" width=\"1200\">\r\n");
      out.write("<table align=\"center\" width=\"1200\" border=\"1px solid #bcbcbc\">\r\n");
      out.write("<tr height=\"40\"><th width=\"600\" colspan=\"2\"><table align=\"center\" width=\"600\" border=\"1px solid #bcbcbc\"><tr height=\"40\">\r\n");
      out.write("<th width=\"150\">브랜드</th><th width=\"280\"><input type=\"text\" name=\"brand\" id=\"brand\"></th><td width=\"170\"> <input type=\"file\" name=\"brandimage\" id=\"brandimage\" ></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table></th>\r\n");
      out.write("<th width=\"300\">사이즈 정보</th>\r\n");
      out.write("<th width=\"300\">\r\n");
      out.write("<input type=\"checkbox\" name=\"sizecategory\" value=\"s\">S<input type=\"checkbox\" name=\"sizecategory\" value=\"m\">M\r\n");
      out.write("<input type=\"checkbox\" name=\"sizecategory\" value=\"l\">L<input type=\"checkbox\" name=\"sizecategory\" value=\"xl\">XL\r\n");
      out.write("</th></tr>\r\n");
      out.write("<tr height=\"40\"><th width=\"300\">분류</th><td width=\"300\"><input type=\"text\" name=\"producttype\" id=\"producttype\"></td><th width=\"600\" colspan=\"2\">사이즈 정보</th></tr>\r\n");
      out.write("<tr height=\"40\"><th>상품이름</th><td><input type=\"text\" name=\"productname\" id=\"productname\"></td>\r\n");
      out.write("<th colspan=\"2\" rowspan=\"4\"><table align=\"center\" width=\"600\" border=\"1px solid #bcbcbc\">\r\n");
      out.write("<tr height=\"30\"><th width=\"150\">SIZE</th><th width=\"150\"><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></th><th width=\"150\"><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></th><th width=\"150\"><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></th></tr>\r\n");
      out.write("<tr height=\"30\"><th><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></th><td><input  type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></td><td><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></td><td><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></td></tr>\r\n");
      out.write("<tr height=\"30\"><th><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></th><td><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></td><td><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></td><td><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></td></tr>\r\n");
      out.write("<tr height=\"30\"><th><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></th><td><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></td><td><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></td><td><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></td></tr>\r\n");
      out.write("<tr height=\"30\"><th><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></th><td><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></td><td><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></td><td><input type=\"text\" name=\"sizecontents\" id=\"sizecontents\"></td></tr>\r\n");
      out.write("</table></th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr height=\"40\"><th>시즌</th><td><input type=\"text\" name=\"season\" id=\"season\"></td></tr>\r\n");
      out.write("<tr height=\"40\"><th>성별</th>\r\n");
      out.write("<td>&nbsp; &nbsp; \r\n");
      out.write("<input type=\"radio\" name=\"sex\" value=\"M\"> 남자 &nbsp; \r\n");
      out.write("<input type=\"radio\" name=\"sex\" value=\"F\"> 여자 &nbsp; \r\n");
      out.write("<input type=\"radio\" name=\"sex\" value=\"U\"> 공용 &nbsp; \r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr height=\"40\"><th>판매가</th><td><input type=\"text\" name=\"productprice\" id=\"productprice\"></td></tr>\r\n");
      out.write("<tr height=\"40\"><th>상품 할인</th><td><input type=\"text\" name=\"discountrate\" id=\"discountrate\"></td><th colspan=\"2\">추가정보</th></tr>\r\n");
      out.write("<tr height=\"40\"><th></th><td></td><th colspan=\"2\" rowspan=\"2\"><textarea cols=\"90\" rows=\"4\" name=\"moreinfo\" id=\"moreinfo\"></textarea></th></tr>\r\n");
      out.write("<tr height=\"40\"><th></th><td></td></tr>\r\n");
      out.write("</table >\r\n");
      out.write("<br>\r\n");
      out.write("<table id=\"productdetail\" align=\"center\" width=\"1200\" border=\"1px solid #bcbcbc\">\r\n");
      out.write("<tr height=\"40\"><th width=\"100\">COLOR</th><th width=\"100\">FULL</th><th width=\"100\">FRONT</th><th width=\"100\">SIDE</th><th width=\"100\">BACK</th><th width=\"100\">PRODUCT</th>\r\n");
      out.write("<th width=\"110\">Ssize재고</th><th width=\"110\">Msize재고</th><th width=\"110\">Lsize재고</th><th width=\"110\">XLsize재고</th><th><button onclick=\"addRow();\">+</button>&nbsp;&nbsp;<button>-</button></th></tr>\r\n");
      out.write("<tr height=\"40\">\r\n");
      out.write("<td align=\"center\" ><input type=\"color\"  name=\"productcolor\" id=\"productcolor\"></td>\r\n");
      out.write("<td><input  type=\"file\" name=\"0productimage1\" id=\"0productimage1\"></div></td>\r\n");
      out.write("<td><input  type=\"file\" name=\"0productimage2\" id=\"0productimage2\"></div></td>\r\n");
      out.write("<td><input  type=\"file\" name=\"0productimage3\" id=\"0productimage3\"></div></td>\r\n");
      out.write("<td><input  type=\"file\" name=\"0productimage4\" id=\"0productimage4\"></div></td>\r\n");
      out.write("<td><input  type=\"file\" name=\"0productimage5\" id=\"0productimage5\"></div></td>\r\n");
      out.write("<td align=\"center\"><input type=\"text\" size=\"10\" name=\"ssizequantity\" id=\"ssizequantity\"></td>\r\n");
      out.write("<td align=\"center\"><input type=\"text\" size=\"10\" name=\"msizequantity\" id=\"msizequantity\"></td>\r\n");
      out.write("<td align=\"center\"><input type=\"text\" size=\"10\" name=\"lsizequantity\" id=\"lsizequantity\"></td>\r\n");
      out.write("<td align=\"center\"><input type=\"text\" size=\"10\" name=\"xlsizequantity\" id=\"xlsizequantity\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<table align=\"center\" >\r\n");
      out.write("<tr align=\"center\" ><th><input type=\"submit\" value=\"등록하기\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button>취소</button></th></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
