/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-20 05:31:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import product.model.vo.ProductFull;
import user.model.vo.LookBomUser;
import java.util.ArrayList;

public final class productDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.model.vo.LookBomUser");
    _jspx_imports_classes.add("product.model.vo.ProductFull");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"productError.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    ArrayList<ProductFull> list = (ArrayList<ProductFull>)request.getAttribute("list"); 


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>lookbom</title> \r\n");
      out.write("<script type=\"text/javascript\" src=\"/lb/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function shoppingbag() {\r\n");
      out.write("location.href =\"/lb/pshoppingbag?pno=\"+$(\"#pno\").val()+\"&pdno=\"+$(\"#pdno\").val()\r\n");
      out.write("\t\t      +\"&size=\"+$(\"#size\").val()+\"&quantity=\"+$(\"#quantity\").val();\r\n");
      out.write("\t}\r\n");
      out.write("function order() {\r\n");
      out.write("\tlocation.href = \"/lb/porder?pno=\"+document.getElementById(\"pno\").value+\"&pdno=\"+document.getElementById(\"pdno\").value\r\n");
      out.write("    +\"&size=\"+document.getElementById(\"size\").value+\"&quantity=\"+document.getElementById(\"quantity\").value;\r\n");
      out.write("\t} \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2 align=\"center\">상품상세페이지 입니다.</h2>\r\n");
      out.write("\r\n");
      out.write("<table align=\"center\" width=\"1000\" border=\"1px solid #bcbcbc\">\r\n");
      out.write("<form name=\"productoption\" id=\"productoption\" method=\"get\" >\r\n");
      out.write("<input type=\"hidden\"  name=\"pno\"  id=\"pno\"  value=\"");
      out.print(list.get(0).getProductNo());
      out.write("\">\r\n");
      out.write("<input type=\"hidden\"  name=\"pdno\"  id=\"pdno\" value=\"");
      out.print(list.get(0).getProductDetailNo());
      out.write("\">\r\n");
      out.write("<tr height=\"520\">\r\n");
      out.write("<th width=\"600\">\r\n");
      out.write("<table width=\"600\" border=\"1px solid #bcbcbc\">\r\n");
      out.write("<tr height=\"40\"><th colspan=\"2\"><div name=\"brandimage\" id=\"brandimgae\"><img width=\"100%\" height=\"100%\" src=\"/lb/file/product/");
      out.print( list.get(0).getBrand_image() );
      out.write("\" ></div></th></tr>\r\n");
      out.write("<tr height=\"120\"><th width=\"130\"><div name=\"productimage2\" id=\"productimage2\"><img width=\"100%\" height=\"100%\" src=\"/lb/file/product/");
      out.print( list.get(0).getProductImage2() );
      out.write("\" ></div></th><th width=\"470\" rowspan=\"4\"><div name=\"productimage1\" id=\"productimage1\"><img width=\"100%\" height=\"100%\" src=\"/lb/file/product/");
      out.print( list.get(0).getProductImage1() );
      out.write("\" ></div></th></tr>\r\n");
      out.write("<tr height=\"120\"><th><div name=\"productimage3\" id=\"productimage3\"><img width=\"100%\" height=\"100%\" src=\"/lb/file/product/");
      out.print( list.get(0).getProductImage3() );
      out.write("\" ></div></th></tr>\r\n");
      out.write("<tr height=\"120\"><th><div name=\"productimage4\" id=\"productimage4\"><img width=\"100%\" height=\"100%\" src=\"/lb/file/product/");
      out.print( list.get(0).getProductImage4() );
      out.write("\" ></div></th></tr>\r\n");
      out.write("<tr height=\"120\"><th><div name=\"productimage5\" id=\"productimage5\"><img width=\"100%\" height=\"100%\" src=\"/lb/file/product/");
      out.print( list.get(0).getProductImage5() );
      out.write("\" ></div></th></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</th>\r\n");
      out.write("<th width=\"400\">\r\n");
      out.write("<table width=\"400\" border=\"1px solid #bcbcbc\">\r\n");
      out.write("<tr height=\"45\"><th colspan=\"4\">상품정보</th></tr>\r\n");
      out.write("<tr height=\"30\"><th >상품명</th><td colspan=\"3\">");
      out.print(list.get(0).getProductName() );
      out.write("</td></tr>\r\n");
      out.write("<tr height=\"30\"><th width=\"100\">브랜드</th><td width=\"100\">");
      out.print( list.get(0).getBrand() );
      out.write("</td><th width=\"100\">품번</th><td width=\"100\">");
      out.print( list.get(0).getProductNo() );
      out.write("</td></tr>\r\n");
      out.write("<tr height=\"30\"><th>시즌</th><td>");
      out.print( list.get(0).getSeason() );
      out.write("</td><th>성별</th><td>");
      out.print( list.get(0).getSex() );
      out.write("</td></tr>\r\n");
      out.write("<tr height=\"30\"><th>조회수</th><td>");
      out.print( list.get(0).getViewCount() );
      out.write("</td><th>총판매량</th><td>");
      out.print( list.get(0).getTotalSaleRate());
      out.write("</td></tr>\r\n");
      out.write("<tr height=\"45\"><th colspan=\"4\">가격정보</th></tr>\r\n");
      out.write("<tr height=\"30\"><th>판매가</th><td colspan=\"3\">");
      out.print( list.get(0).getProductPrice());
      out.write("</td></tr>\r\n");
      out.write("<tr height=\"30\"><th>할인률</th><td colspan=\"3\">");
      out.print( list.get(0).getDiscountRate() );
      out.write("</td></tr>\r\n");
      out.write("<tr height=\"30\"><th>할인된 가격</th><td colspan=\"3\">");
      out.print( (int)(list.get(0).getProductPrice()-(list.get(0).getProductPrice()*list.get(0).getDiscountRate())) );
      out.write("</td></tr>\r\n");
      out.write("<tr height=\"45\"><th colspan=\"4\">색상</th></tr>\r\n");
      out.write("<tr height=\"60\">\r\n");
  for(int i=0;i<list.size();i++){       

      out.write("\r\n");
      out.write("<th><button style=\"width:30px;height:30px;background-color:");
      out.print(list.get(i).getProductColor());
      out.write(";\"></button></th>\r\n");
 } 
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("<tr height=\"50\">\r\n");
      out.write("<th colspan=\"2\">사이즈 :\r\n");
      out.write("<input type=\"text\" name=\"size\" id=\"size\" list=\"sizelist\" size=\"10\" >\r\n");
      out.write("       <datalist id=\"sizelist\">      \r\n");
  String[] sizecategory = list.get(0).getSizeCategory().split(",");
       for(int i=0;i<sizecategory.length;i++){
 
      out.write("       \r\n");
      out.write("       <option value=\"");
      out.print( sizecategory[i]);
      out.write("\"></option>     \r\n");
 } 
      out.write("       \r\n");
      out.write("</datalist>\r\n");
      out.write("</th>\r\n");
      out.write("<th colspan=\"2\">수량 : \r\n");
      out.write("<input type=\"number\" name=\"quantity\" id=\"quantity\" min=\"1\" max=\"100\" step=\"1\" value=\"1\">\r\n");
      out.write("</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</form>\r\n");
      out.write("<tr height=\"50\"><th colspan=\"2\"><button type=\"submit\" onclick=\"shoppingbag();\">장바구니</th>\r\n");
      out.write("<th colspan=\"2\"><button onclick=\"order();\">주문하기</th></tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr height=\"230\">\r\n");
      out.write("<th>\r\n");
      out.write("<table width=\"600\" border=\"1px solid #bcbcbc\">\r\n");
 String[] sizecontents = list.get(0).getSizeContents().split(",");	
 

      out.write("\r\n");
      out.write("<tr height=\"40\"><th width=\"150\">SIZE</th><th width=\"150\">");
      out.print( sizecontents[0]);
      out.write("</th><th width=\"150\">");
      out.print(sizecontents[1]);
      out.write("</th><th width=\"150\">");
      out.print(sizecontents[2]);
      out.write("</th></tr>\r\n");
      out.write("<tr height=\"40\"><th>");
      out.print(sizecontents[3]);
      out.write("</th><td>");
      out.print(sizecontents[4]);
      out.write("</td><td>");
      out.print(sizecontents[5]);
      out.write("</td><td>");
      out.print(sizecontents[6]);
      out.write("</td></tr>\r\n");
      out.write("<tr height=\"40\"><th>");
      out.print(sizecontents[7]);
      out.write("</th><td>");
      out.print(sizecontents[8]);
      out.write("</td><td>");
      out.print(sizecontents[9]);
      out.write("</td><td>");
      out.print(sizecontents[10]);
      out.write("</td></tr>\r\n");
      out.write("<tr height=\"40\"><th>");
      out.print(sizecontents[11]);
      out.write("</th><td>");
      out.print(sizecontents[12]);
      out.write("</td><td>");
      out.print(sizecontents[13]);
      out.write("</td><td>");
      out.print(sizecontents[14]);
      out.write("</td></tr>\r\n");
      out.write("<tr height=\"40\"><th>");
      out.print(sizecontents[15]);
      out.write("</th><td>");
      out.print(sizecontents[16]);
      out.write("</td><td>");
      out.print(sizecontents[17]);
      out.write("</td><td>");
      out.print(sizecontents[18]);
      out.write("</td></tr> \r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("<table width=\"400\" border=\"1px solid #bcbcbc\">\r\n");
      out.write("<tr height=\"45\"><th>추가정보</th></tr>\r\n");
      out.write("<tr height=\"160\"><td>");
      out.print( list.get(0).getMoreInto());
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
